apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: podinfo.corp.com.1.0.0
spec:
  refName: podinfo.corp.com
  version: 1.0.0
  releaseNotes: |
    Initial release of the Podinfo App package
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        replicas:
          type: integer
          default: 5
        ui_color:
          type: string
          default: blue
        svc_port:
          type: integer
          default: 80
        app_port:
          type: integer
          default: 9898
        svc_type:
          type: string
          default: LoadBalancer
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: masanara/podinfo:1.0.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
